from datetime import datetime, date, time, timedelta

d = date(2025, 7, 6)
print(d)
print(type(d))
t = time(20, 45)
print(t)
print(type(t))

dt = datetime.combine(d, t)
print(dt)
print(type(dt))
print(d.year)
print(d.month)
print(d.day)
cld = dt.isocalendar()
for i in cld:
    print(i)
print(d.weekday())
print('---------')
inf = dt.timetuple()
for i in inf:
    print(i)
print(dt.strftime('%A %d %B %Y  %I:%M %p'))
# print(date.today().replace(day=5, month=3))
print(datetime.now())
print(datetime.now().date())
print(datetime.now().time())
print(datetime.strftime(datetime.now(), '%H:%M:%S'))
print(datetime.now().strftime('%H:%M:%S'))
print(datetime.utcnow())
# print(datetime.strptime('16.06.2025 12:20:12', '%d.%m.%Y %H:%M:%S'))
# print(datetime.strptime('16.06.2025 12:20:12', '%d.%m.%Y %X'))
nw = datetime.strptime('16.08.2025 12:20:12', '%d.%m.%Y %X')
print(type(nw))
wn = datetime.now()
# print(nw.year)
# nw = nw.replace(year=nw.year + 1)
print(nw - wn)
print(wn + timedelta(days=100))